name: influenza_nanopore
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - medaka=1.6.0
  - seqtk
  - spoa
  - snakemake
  - centrifuge=1.0.4
  - porechop=0.2.4
  - r-base
  - r-tidyverse
  - r-pastecs
  - r-rmarkdown
  - r-knitr
  - r-data.table
  - r-plotly
  - r-scales
  - r-ggridges